# Generated by Django 5.2.16 on 2026-08-03 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appt_date", models.DateField(blank=True, null=True)),
                ("appt_slot", models.CharField(blank=True, max_length=20, null=True)),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("outcome_recorded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "outcome_recorded_by_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "outcome_recorded_by_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "cancelled_by_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "cancelled_by_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
            options={
                "db_table": "appointments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BankStaff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "Bank staff",
                "db_table": "bank_staff",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="BankStaffAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("work_date", models.DateField(blank=True, null=True)),
                ("shift_start", models.CharField(blank=True, max_length=20, null=True)),
                ("shift_end", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "bank_staff_assignments",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("encounter_type", models.CharField(max_length=60)),
                ("encounter_date", models.DateField()),
                (
                    "encounter_time",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "recorded_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "encounters",
                "ordering": ["-encounter_date"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pathway_type",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("created_by", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("surgery_date", models.DateField(blank=True, null=True)),
                ("post_op_start", models.DateField(blank=True, null=True)),
            ],
            options={
                "db_table": "episodes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EpisodeStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("step_no", models.IntegerField(blank=True, null=True)),
                ("step_key", models.CharField(blank=True, max_length=60, null=True)),
                ("status", models.CharField(blank=True, max_length=30, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
                (
                    "completed_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "episode_steps",
                "ordering": ["step_no"],
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FollowupSeenEpisode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "episode_code",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "base_episode_code",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("version_number", models.IntegerField(blank=True, null=True)),
                (
                    "full_episode_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("review_date", models.DateField(blank=True, null=True)),
                (
                    "patient_id_card",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "patient_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "stoma_colour",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "stoma_colour_other",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "stoma_function",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "stoma_function_other",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "peristomal_skin",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                (
                    "peristomal_skin_other",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("appliances_used", models.JSONField(blank=True, null=True)),
                ("accessories_used", models.JSONField(blank=True, null=True)),
                (
                    "followup_owner",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("followup_due_month", models.IntegerField(blank=True, null=True)),
                ("followup_year", models.IntegerField(blank=True, null=True)),
                (
                    "followup_status",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("nursing_report", models.TextField(blank=True, null=True)),
                ("episode_data", models.JSONField(blank=True, null=True)),
                ("changed_fields", models.JSONField(blank=True, null=True)),
                (
                    "recorded_by_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "recorded_by_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "followup_seen_episodes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LeaveRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("leave_type", models.CharField(blank=True, max_length=40, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("total_days", models.IntegerField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "leave_records",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id_card", models.CharField(blank=True, max_length=50, null=True)),
                ("first_name", models.CharField(blank=True, max_length=120, null=True)),
                ("surname", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("dob", models.DateField(blank=True, null=True)),
                ("locality", models.CharField(blank=True, max_length=120, null=True)),
                ("sex", models.CharField(blank=True, max_length=20, null=True)),
                ("surgery_date", models.DateField(blank=True, null=True)),
                ("planned_surgery_date", models.DateField(blank=True, null=True)),
                (
                    "inpatient_type",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "admission_route",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("operation_performed", models.TextField(blank=True, null=True)),
                (
                    "surgery_event_operation_performed",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "surgery_type",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("consultant", models.CharField(blank=True, max_length=120, null=True)),
                ("findings", models.TextField(blank=True, null=True)),
                ("stoma_type_summary", models.TextField(blank=True, null=True)),
                ("past_medical_history", models.TextField(blank=True, null=True)),
                ("past_surgical_history", models.TextField(blank=True, null=True)),
                ("drug_history", models.TextField(blank=True, null=True)),
                ("medication_history", models.JSONField(blank=True, null=True)),
                ("medication_history_other", models.TextField(blank=True, null=True)),
                (
                    "medication_additional_notes",
                    models.TextField(blank=True, null=True),
                ),
                ("social_history", models.TextField(blank=True, null=True)),
                ("dpa_status", models.CharField(blank=True, max_length=60, null=True)),
                ("clinical_complications", models.TextField(blank=True, null=True)),
                (
                    "followup_owner",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("followup_due_month", models.IntegerField(blank=True, null=True)),
                ("followup_year", models.IntegerField(blank=True, null=True)),
                (
                    "followup_status",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "followup_type",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("next_followup_mirror", models.DateField(blank=True, null=True)),
                ("reversal_date", models.DateField(blank=True, null=True)),
                ("rip_date", models.DateField(blank=True, null=True)),
                ("discharged_date", models.DateField(blank=True, null=True)),
                ("last_outcome_date", models.DateField(blank=True, null=True)),
                ("active_registry", models.BooleanField(blank=True, null=True)),
                (
                    "patient_status_raw",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("stoma_days", models.IntegerField(blank=True, null=True)),
                ("age_at_death", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "patients",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PublicHoliday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("holiday_date", models.DateField()),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "public_holidays",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Roster",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("roster_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=40, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "roster",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name_plural": "Staff",
                "db_table": "staff",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="OrderingDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=60, unique=True)),
                ("form_type", models.CharField(default="ESRF STO-01", max_length=40)),
                (
                    "section_ward",
                    models.CharField(default="Stoma Care", max_length=120),
                ),
                ("cost_centre", models.CharField(default="STO-01", max_length=40)),
                ("ext_no", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "delivery_period",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("items", models.JSONField(blank=True, default=list)),
                (
                    "requested_by_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "requested_by_username",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("form_date", models.DateField(blank=True, null=True)),
                (
                    "recipient_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("saved", "Saved (not emailed)")],
                        default="saved",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ordering_documents",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
    ]
