# Generated by Django 5.2.16 on 2026-08-04 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenderEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(default="Untitled tender", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("bidder_count", models.IntegerField(default=0)),
                ("lowest_bid", models.FloatField(blank=True, null=True)),
                (
                    "lowest_bidder",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "created_by_username",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tender_evaluations",
                "ordering": ["-updated_at"],
                "managed": True,
            },
        ),
    ]
