# Generated by Django 5.2.16 on 2026-08-05 19:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_tenderevaluation"),
    ]

    operations = [
        migrations.CreateModel(
            name="CarePathway",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pathway_type",
                    models.CharField(
                        choices=[
                            ("elective", "Elective"),
                            ("emergency", "Emergency"),
                            ("old_case", "Old case (operated elsewhere)"),
                            ("fistula", "Fistula"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("siting_scheduled", "Siting scheduled"),
                            ("awaiting_surgery", "Awaiting surgery"),
                            ("inpatient", "Inpatient — under review"),
                            ("outpatient", "Outpatient"),
                            ("discharged", "Discharged"),
                            ("followup", "Follow-up (old stoma)"),
                            ("closed", "Closed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "referral_source",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "care_setting",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("inpatient", "Inpatient"),
                            ("outpatient", "Outpatient appointment"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("siting_scheduled_date", models.DateField(blank=True, null=True)),
                ("siting_done_date", models.DateField(blank=True, null=True)),
                ("siting_chart", models.JSONField(blank=True, default=dict)),
                ("surgery_date", models.DateField(blank=True, null=True)),
                ("stoma_type", models.CharField(blank=True, max_length=120, null=True)),
                ("operation", models.CharField(blank=True, max_length=200, null=True)),
                ("first_review_date", models.DateField(blank=True, null=True)),
                ("discharge_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "created_by_username",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_pathways",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "db_table": "care_pathways",
                "ordering": ["-updated_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FollowUpAppointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appt_date", models.DateField()),
                ("appt_time", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("attended", "Attended"),
                            ("postponed", "Postponed"),
                            ("cancelled", "Cancelled"),
                            ("dna", "Did not attend"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pathway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followup_appointments",
                        to="clinic.carepathway",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followup_appointments_new",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "db_table": "followup_appointments",
                "ordering": ["appt_date", "appt_time"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PathwayEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("siting", "Stoma siting session"),
                            ("surgery", "Surgery"),
                            ("post_op_review", "Post-operative review"),
                            ("review", "Review"),
                            ("discharge", "Discharge"),
                            ("followup", "Follow-up review"),
                            ("note", "Note"),
                        ],
                        default="review",
                        max_length=20,
                    ),
                ),
                ("event_date", models.DateField()),
                ("day_number", models.IntegerField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=250, null=True)),
                ("education_given", models.BooleanField(default=False)),
                ("supplies_given", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "recorded_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pathway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="clinic.carepathway",
                    ),
                ),
            ],
            options={
                "db_table": "pathway_events",
                "ordering": ["-event_date", "-created_at"],
                "managed": True,
            },
        ),
    ]
