# Generated by Django 5.2.16 on 2026-08-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_carepathway_followupappointment_pathwayevent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pathwayevent",
            options={
                "managed": True,
                "ordering": ["-event_date", "-sequence", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="carepathway",
            name="episode_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=30, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="pathwayevent",
            name="encounter_number",
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="pathwayevent",
            name="sequence",
            field=models.IntegerField(default=0),
        ),
    ]
