# Generated by Django 5.2.16 on 2026-08-06 05:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0005_backfill_episode_numbers"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stoma",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "stoma_ref",
                    models.CharField(
                        blank=True, db_index=True, max_length=30, null=True, unique=True
                    ),
                ),
                (
                    "stoma_type",
                    models.CharField(
                        choices=[
                            ("colostomy", "Colostomy"),
                            ("ileostomy", "Ileostomy"),
                            ("urostomy", "Urostomy"),
                            ("jejunostomy", "Jejunostomy"),
                            ("mucous_fistula", "Mucous fistula"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "site",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LIF", "Left iliac fossa"),
                            ("RIF", "Right iliac fossa"),
                            ("LUQ", "Left upper quadrant"),
                            ("RUQ", "Right upper quadrant"),
                            ("umbilical", "Umbilical"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("formed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("refashioned", "Refashioned"),
                            ("resited", "Resited"),
                            ("closed", "Closed"),
                            ("reversed", "Reversed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("ended_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pathway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stomas",
                        to="clinic.carepathway",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stomas",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "db_table": "stomas",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ApplianceRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("used_on", models.DateField()),
                (
                    "system",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("one_piece", "One-piece"),
                            ("two_piece", "Two-piece"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("pouch_type", models.CharField(blank=True, max_length=60, null=True)),
                ("brand", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("size", models.CharField(blank=True, max_length=60, null=True)),
                (
                    "accessories",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("changed", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appliances",
                        to="clinic.pathwayevent",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appliance_records",
                        to="clinic.patient",
                    ),
                ),
                (
                    "stoma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appliances",
                        to="clinic.stoma",
                    ),
                ),
            ],
            options={
                "db_table": "appliance_records",
                "ordering": ["-used_on", "-created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StomaAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessed_on", models.DateField()),
                ("colour", models.CharField(blank=True, max_length=40, null=True)),
                ("output", models.CharField(blank=True, max_length=80, null=True)),
                ("output_ml", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "peristomal_skin",
                    models.CharField(blank=True, max_length=60, null=True),
                ),
                (
                    "stoma_height",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "complications",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="clinic.pathwayevent",
                    ),
                ),
                (
                    "stoma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="clinic.stoma",
                    ),
                ),
            ],
            options={
                "db_table": "stoma_assessments",
                "ordering": ["-assessed_on", "-created_at"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="StomaChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("refashioned", "Refashioned"),
                            ("resited", "Resited"),
                            ("closed", "Closed"),
                            ("reversed", "Reversed"),
                            ("revised", "Revised"),
                        ],
                        max_length=20,
                    ),
                ),
                ("change_date", models.DateField()),
                ("new_site", models.CharField(blank=True, max_length=20, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "recorded_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stoma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="clinic.stoma",
                    ),
                ),
            ],
            options={
                "db_table": "stoma_changes",
                "ordering": ["-change_date", "-created_at"],
                "managed": True,
            },
        ),
    ]
