# Generated by Django 5.2.16 on 2026-08-06 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0006_stoma_appliancerecord_stomaassessment_stomachange"),
    ]

    operations = [
        migrations.CreateModel(
            name="LibraryDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("protocol", "Protocol"),
                            ("guideline", "Guideline"),
                            ("patient_info", "Patient information"),
                            ("form", "Form / template"),
                            ("audit", "Audit & compliance"),
                            ("education", "Education & training"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("file", models.FileField(upload_to="library/%Y/%m/")),
                (
                    "original_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                (
                    "uploaded_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "library_documents",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
    ]
