# Generated by Django 5.2.16 on 2026-08-06 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0007_librarydocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="librarydocument",
            name="auto_filed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="librarydocument",
            name="patient",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="library_documents",
                to="clinic.patient",
            ),
        ),
        migrations.AddField(
            model_name="librarydocument",
            name="reference",
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name="librarydocument",
            name="source",
            field=models.CharField(
                choices=[
                    ("upload", "Uploaded"),
                    ("requisition", "Requisition sent"),
                    ("discharge_letter", "Discharge letter"),
                    ("tender", "Tender closed"),
                ],
                default="upload",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="librarydocument",
            name="category",
            field=models.CharField(
                choices=[
                    ("correspondence", "Email correspondence"),
                    ("requisition", "Ordering form / requisition"),
                    ("discharge_letter", "Discharge letter"),
                    ("tender", "Tender evaluation"),
                    ("protocol", "Protocol"),
                    ("guideline", "Guideline"),
                    ("patient_info", "Patient information"),
                    ("form", "Form / template"),
                    ("audit", "Audit & compliance"),
                    ("education", "Education & training"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
