# Generated by Django 5.2.16 on 2026-08-06 14:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0008_librarydocument_auto_filed_librarydocument_patient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplianceCatalogueItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("appliance", "Appliance"),
                            ("accessory", "Accessory"),
                        ],
                        default="appliance",
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("brand", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "product_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. one-piece drainable, urostomy, paste, belt",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("on_contract", models.BooleanField(default=False)),
                (
                    "created_by_username",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "appliance_catalogue",
                "ordering": ["item_type", "name"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "product_group",
                    models.CharField(
                        blank=True,
                        help_text="e.g. colostomy appliances, urostomy, accessories",
                        max_length=150,
                        null=True,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("specification", models.TextField(blank=True, null=True)),
                ("mandatory", models.BooleanField(default=True)),
                (
                    "created_by_username",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "product_specifications",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
    ]
