# Generated by Django 5.2.16 on 2026-08-06 15:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0009_appliancecatalogueitem_productspecification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "recipient_email",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "One-off"),
                            ("daily", "Every day"),
                            ("weekly", "Every week"),
                            ("monthly", "Every month"),
                        ],
                        default="weekly",
                        max_length=10,
                    ),
                ),
                (
                    "weekday",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        null=True,
                    ),
                ),
                ("day_of_month", models.IntegerField(blank=True, null=True)),
                ("on_date", models.DateField(blank=True, null=True)),
                ("at_time", models.TimeField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("action_url", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "action_label",
                    models.CharField(blank=True, max_length=80, null=True),
                ),
                ("created_by", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "reminders",
                "ordering": ["-active", "weekday", "title"],
                "managed": True,
            },
        ),
    ]
