# Generated by Django 5.2.16 on 2026-08-06 16:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0011_seed_mml_reminder"),
    ]

    operations = [
        migrations.CreateModel(
            name="RosterStaff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("role", models.CharField(blank=True, max_length=120, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("core", "Core staff"),
                            ("overtime", "Overtime staff"),
                        ],
                        default="core",
                        max_length=12,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "roster_staff",
                "ordering": ["category", "display_order", "full_name"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="RosterShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("code", models.CharField(max_length=10)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="clinic.rosterstaff",
                    ),
                ),
            ],
            options={
                "db_table": "roster_shifts",
                "ordering": ["date"],
                "managed": True,
                "unique_together": {("staff", "date")},
            },
        ),
    ]
