# Generated by Django 5.2.17 on 2026-08-10 15:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0014_diaryentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=6)),
                ("notes", models.CharField(blank=True, max_length=300, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="overtime_hours",
                        to="clinic.rosterstaff",
                    ),
                ),
            ],
            options={
                "db_table": "roster_overtime_hours",
                "ordering": ["-date"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="TimeinLieuHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[("earned", "Earned"), ("used", "Used")],
                        default="earned",
                        max_length=6,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="til_hours",
                        to="clinic.rosterstaff",
                    ),
                ),
            ],
            options={
                "db_table": "roster_til_hours",
                "ordering": ["-date"],
                "managed": True,
            },
        ),
    ]
