# Generated by Django 5.2.17 on 2026-08-12 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0015_overtimehours_timeinlieuhours"),
    ]

    operations = [
        migrations.AddField(
            model_name="followupappointment",
            name="next_followup_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followupappointment",
            name="nurse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinic_appointments",
                to="clinic.rosterstaff",
            ),
        ),
        migrations.AddField(
            model_name="followupappointment",
            name="outcome_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="followupappointment",
            name="outcome_by",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="AppointmentCancellation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appt_date", models.DateField(blank=True, null=True)),
                ("appt_time", models.CharField(blank=True, max_length=20, null=True)),
                ("nurse_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("patient_request", "Patient request"),
                            ("illness", "Illness"),
                            ("transport", "Transport"),
                            ("clinical", "Clinical decision"),
                            ("rescheduled", "Rescheduled"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=400, null=True)),
                (
                    "cancelled_by",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cancelled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointment_cancellations",
                        to="clinic.patient",
                    ),
                ),
            ],
            options={
                "db_table": "appointment_cancellations",
                "ordering": ["-cancelled_at"],
                "managed": True,
            },
        ),
    ]
