# Generated by Django 5.2.17 on 2026-08-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0016_followupappointment_next_followup_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointmentcancellation",
            name="reason",
            field=models.CharField(
                choices=[
                    ("patient_cancelled", "Patient cancelled the appointment"),
                    ("clinic_cancelled", "Appointment cancelled by the clinic"),
                    ("reviewed_ward", "Cancelled — patient reviewed on the ward"),
                    ("awaiting_surgery", "Awaiting surgery"),
                    ("awaiting_feedback", "Awaiting feedback"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
