"""Stationery / SIT request stock list (STO-01), from Sationary_STO01.xlsx.

Each item is a dict: code, description, unit, quota (reference quota from
the master list; blank where none). Staff fill in the Demand column.
"""

STATIONERY_ITEMS = [
    {"code": '07ADHES005', "description": 'ADHESIVE TAPE', "unit": '', "quota": ''},
    {"code": '01BANDS070', "description": 'BANDS RUBBER', "unit": 'GRAMS 100', "quota": ''},
    {"code": '01BANDS075', "description": 'BANDS RUBBER THICK', "unit": '', "quota": '1'},
    {"code": '10BATTE045', "description": 'BATTERIES ALKALINE 12V', "unit": 'NUMBER', "quota": ''},
    {"code": '10BATTE005', "description": 'BATTERIES ALKALINE 9V 6LF22-9V', "unit": 'NUMBER', "quota": ''},
    {"code": '10BATTE015', "description": 'BATTERIES ALKALINE AAA-LR03-AM-4', "unit": 'NUMBER', "quota": ''},
    {"code": '10BATTE010', "description": 'BATTERIES ALKALINE AA-LR6-AM-3', "unit": 'NUMBER X 4', "quota": '8'},
    {"code": '10BATTE030', "description": 'BATTERIES ALKALINE C-LR14-UM-2 (MEDIUM)', "unit": 'NUMBER', "quota": ''},
    {"code": '10BATTE035', "description": 'BATTERIES ALKALINE D-LR20-UM-1 (LARGE)', "unit": 'NUMBER', "quota": ''},
    {"code": '10BATTE040', "description": 'BATTERIES ALKALINE NO.867 SIZE J 6V ALKALINE', "unit": 'NUMBER', "quota": ''},
    {"code": '10BATTE050', "description": 'BATTERIES ROUND FLAT V76PX-SR44', "unit": 'NUMBER', "quota": ''},
    {"code": '09BIROS006', "description": 'BIRO BLACK', "unit": 'Number', "quota": '2'},
    {"code": '09BIROS005', "description": 'BIRO BLUE', "unit": 'Number', "quota": '2'},
    {"code": '09BIROS007', "description": 'BIRO RED', "unit": 'Number', "quota": '2'},
    {"code": '09BIROS010', "description": 'BIRO GREEN', "unit": 'Number', "quota": ''},
    {"code": '15BRACE005', "description": 'BRACELETS I.D.PEADIATRIC', "unit": '', "quota": ''},
    {"code": '15BRACE010', "description": 'BRACELETS I.D. ADULTS', "unit": '', "quota": ''},
    {"code": '15BRACE015', "description": 'BANDS WRIST TYPE PAEDIATRIC COLOUR', "unit": '', "quota": ''},
    {"code": '15BRACE020', "description": 'BANDS WRIST TYPE ADULTS COLOUR', "unit": '', "quota": ''},
    {"code": '05BLOTT015', "description": 'BLOTTING PAPER', "unit": '', "quota": ''},
    {"code": '07BKARO', "description": 'BLANCO ROLLER', "unit": '', "quota": ''},
    {"code": '01BLUET020', "description": 'BLUE TACK', "unit": '', "quota": ''},
    {"code": '01BOWLS007', "description": 'BOWLS SOUP PLASTIC DISPOSABLE', "unit": '', "quota": ''},
    {"code": '05BOXFI145', "description": 'BOX FILES', "unit": 'Number', "quota": '4'},
    {"code": '05BROWN010', "description": 'BROWN PAPER', "unit": 'Number', "quota": ''},
    {"code": '01BULLD010', "description": 'BULLDOG CLIPS LARGE', "unit": 'Number', "quota": ''},
    {"code": '01BULLD005', "description": 'BULLDOG CLIPS SMALL', "unit": 'Number', "quota": ''},
    {"code": '01CALCU005', "description": 'CALCULATOR', "unit": 'Number', "quota": ''},
    {"code": '05CARBO020', "description": 'CARBON PAPER (A4) BLACK', "unit": 'BOX', "quota": ''},
    {"code": '05CARBO020', "description": 'CARBON PAPER (A4) BLUE', "unit": 'BOX', "quota": ''},
    {"code": '01CLIPP050', "description": 'CLIPS PAPER SMALL SIZE', "unit": 'BOX', "quota": '1'},
    {"code": '01CLIPB001', "description": 'PLASTIC CLIP BOARD', "unit": '', "quota": ''},
    {"code": '01CORRE012', "description": 'CORRECTING FLUID (PEN)', "unit": '', "quota": ''},
    {"code": '01CORRE010', "description": 'CORRECTING FLUID (TIPEX)', "unit": 'Number', "quota": '1'},
    {"code": '07BKAR0', "description": 'TIPPEX MOUSE', "unit": 'Number', "quota": ''},
    {"code": '05DASF0185', "description": 'DAS FORMS ACC 2A', "unit": '', "quota": ''},
    {"code": '01DAMPE030', "description": 'DAMPER SPONGE BOWL', "unit": '', "quota": ''},
    {"code": '01DESK001', "description": 'DESK ORGANISER', "unit": '', "quota": ''},
    {"code": '05DESKP180', "description": 'DESK PADS', "unit": 'Number', "quota": ''},
    {"code": '01PLAST060', "description": 'DIVIDERS PLASTIC', "unit": '', "quota": ''},
    {"code": '01PLAST065', "description": 'DIVIDERS PLASTIC A- Z', "unit": '', "quota": ''},
    {"code": '01DRAWI035', "description": 'DRAWING PINS', "unit": 'BOX', "quota": '1'},
    {"code": '05ENVEL065', "description": 'ENVELOPES BROWN (INVESTA)', "unit": 'Number', "quota": ''},
    {"code": '05ENVEL080', "description": 'ENVELOPES BROWN WITH TRANSPARENT WINDOW', "unit": 'Number', "quota": ''},
    {"code": '05ENVEL070', "description": 'ENVELOPES PADDED : SMALL', "unit": 'Number', "quota": ''},
    {"code": '05ENVEL071', "description": 'ENVELOPES PADDED : LARGE', "unit": 'Number', "quota": ''},
    {"code": '05FAXRO80', "description": 'FAX ROLLS 210', "unit": 'ROLLS', "quota": ''},
    {"code": '05FAXRO80', "description": 'FAX ROLLS 216', "unit": 'ROLLS', "quota": ''},
    {"code": '09FINLI050', "description": 'FINE LINER BLACK', "unit": 'Number', "quota": ''},
    {"code": '09FINLI050', "description": 'FINE LINER BLUE', "unit": 'Number', "quota": ''},
    {"code": '09FINLI050', "description": 'FINE LINER GREEN', "unit": 'Number', "quota": ''},
    {"code": '09FINLI050', "description": 'FINE LINER RED', "unit": 'Number', "quota": ''},
    {"code": '01FLIPC005', "description": 'FLIP CHART FOR WHITE BOARD', "unit": 'Number', "quota": ''},
    {"code": '01PLAST050', "description": 'FOLDING PLASTIC L SHAPED', "unit": '', "quota": ''},
    {"code": '05GREYF005', "description": 'GREY FILES', "unit": 'PACK x 50', "quota": ''},
    {"code": '05GREEN005', "description": 'GREEN FILES', "unit": 'PACK x 50', "quota": ''},
    {"code": '01GLOY040', "description": 'MULTI PURPOSE GLOY', "unit": '', "quota": ''},
    {"code": '09HIGH01/P', "description": 'HIGHLIGHTER PINK', "unit": 'Number', "quota": '1'},
    {"code": '09HIGH01/P', "description": 'HIGHLIGHTER YELLOW', "unit": 'Number', "quota": '1'},
    {"code": '07INKBA020', "description": 'INK ENDORSING - BLACK', "unit": 'Number', "quota": ''},
    {"code": '07INKBLU025', "description": 'INK ENDORSING - BLUE', "unit": 'Number', "quota": ''},
    {"code": '07INKRE015', "description": 'INK ENDORSING - RED', "unit": 'Number', "quota": ''},
    {"code": '01KEY001', "description": 'KEY TAGS', "unit": 'Number', "quota": ''},
    {"code": '05LASLA03', "description": 'LASER LABELS 70X36MM', "unit": 'BOX X 100 SHTS', "quota": ''},
    {"code": '05LASLA01', "description": 'LASER LABELS 105X37MM', "unit": 'BOX X 100 SHTS', "quota": ''},
    {"code": '05LASLA00', "description": 'LASER LABELS 105X35MM', "unit": 'BOX X 100 SHTS', "quota": ''},
    {"code": '05LASLA02', "description": 'LASER LABELS 70X37MM', "unit": 'BOX X 100 SHTS', "quota": ''},
    {"code": '05LETA4045', "description": 'LETTERHEADS A4', "unit": '', "quota": ''},
    {"code": '05LETA5040', "description": 'LETTERHEADS A5', "unit": '', "quota": ''},
    {"code": '05LEVER100', "description": 'LEVER ARCH FILES', "unit": 'Number', "quota": '1'},
    {"code": '05MAGRA005', "description": 'MAGAZINE RACKS', "unit": 'Number', "quota": ''},
    {"code": '09MARKE035', "description": 'MARKER NON-PERMANENT BLACK', "unit": 'Number', "quota": ''},
    {"code": '09MARKE035', "description": 'MARKER NON-PERMANENT BLUE', "unit": 'Number', "quota": ''},
    {"code": '09MARKE035', "description": 'MARKER NON-PERMANENT GREEN', "unit": 'Number', "quota": ''},
    {"code": '09MARKE035', "description": 'MARKER NON-PERMANENT RED', "unit": 'Number', "quota": ''},
    {"code": '09MARKE030/BLK', "description": 'MARKER PERMANENT BLACK', "unit": 'Number', "quota": '1'},
    {"code": '09MARKE045', "description": 'MARKERS WHITE BOARDS', "unit": '', "quota": ''},
    {"code": '01RISER01', "description": 'METAL RISERS FOR TRAYS', "unit": 'Number', "quota": ''},
    {"code": '01TRANCASE', "description": 'MIGRATION BOXES', "unit": 'Number', "quota": ''},
    {"code": '05MINSH055', "description": 'MINUTE SHEETS', "unit": '', "quota": ''},
    {"code": '09PENCI015', "description": 'PENCIL (BLACK)', "unit": 'Number', "quota": '1'},
    {"code": '09PENSH055', "description": 'PENCIL SHARPENERS', "unit": 'Number', "quota": ''},
    {"code": '09PENCI020', "description": 'PENCILS (BLUE)', "unit": 'Number', "quota": ''},
    {"code": '09PENCI020', "description": 'PENCILS (RED)', "unit": 'Number', "quota": ''},
    {"code": '05PAPERA3', "description": 'PHOTOCOPY PAPER A3 WHITE', "unit": 'REAMS', "quota": ''},
    {"code": '05PHOTO190/BLU', "description": 'PHOTOCOPY PAPER A4 COLOUR  BLUE', "unit": 'REAMS', "quota": '1'},
    {"code": '05PHOTO190/G', "description": 'PHOTOCOPY PAPER A4 COLOUR  GREEN', "unit": 'REAMS', "quota": '1'},
    {"code": '05PHOTO190/P', "description": 'PHOTOCOPY PAPER A4 COLOUR  PINK', "unit": 'REAMS', "quota": '1'},
    {"code": '05PHOTO190/Y', "description": 'PHOTOCOPY PAPER A4 COLOUR  YELLOW', "unit": 'REAMS', "quota": '1'},
    {"code": '05PHOTO185', "description": 'PHOTOCOPY PAPER A4 WHITE WITH WATERMARK', "unit": 'REAMS', "quota": '2'},
    {"code": '01PLAST055', "description": 'PLASTIC DESK TRAYS', "unit": 'Number', "quota": ''},
    {"code": '01PLAST140', "description": 'PLASTIC FOLDER', "unit": 'BOX OF 100', "quota": '1'},
    {"code": '01PLAST145', "description": 'PLASTIC FOLDER VARIOUS COLOURED BACK', "unit": 'BOX OF 10', "quota": '10'},
    {"code": '01PLAST155', "description": 'PLASTIC FOLDERS WITH BUTTON', "unit": '', "quota": ''},
    {"code": '01PLATE030', "description": 'PLATES FLAT BIODEGRADEABLE 10"', "unit": '', "quota": ''},
    {"code": '01PLAST150', "description": 'POUCHES LAMINATING A4', "unit": 'PKTS', "quota": ''},
    {"code": '01PLAST151', "description": 'POUCHES LAMINATING A3', "unit": 'PKTS', "quota": ''},
    {"code": '01PUNCH060', "description": 'PUNCHER (SINGLE)', "unit": '', "quota": ''},
    {"code": '05REGIS110', "description": 'REGISTERS (HALF)', "unit": 'Number', "quota": ''},
    {"code": '01RING01', "description": 'REINFORCEMENT RINGS', "unit": 'Number', "quota": ''},
    {"code": '05RINGF130', "description": 'RING FILES', "unit": 'Number', "quota": '1'},
    {"code": '01DAMPE075', "description": 'ROLLER DAMPER', "unit": 'Number', "quota": ''},
    {"code": '05RUPAP010', "description": 'RULED PAPER A3 (FULL SCAPS)', "unit": 'PACK x 50', "quota": ''},
    {"code": '01RULER105', "description": 'RULERS (30cm)', "unit": 'Number', "quota": ''},
    {"code": '05CONTA170', "description": 'SELF STICK NOTES LARGE', "unit": 'Number', "quota": '1'},
    {"code": '05CONTA165', "description": 'SELF STICK NOTES MEDIUM', "unit": 'Number', "quota": '1'},
    {"code": '05CONTA160', "description": 'SELF STICK NOTES SMALL', "unit": 'Number', "quota": '1'},
    {"code": '01DAMPE030', "description": 'SPANGE BOWL', "unit": 'Number', "quota": ''},
    {"code": '01STAMP090', "description": 'STAMP PADS (BLACK)', "unit": 'Number', "quota": ''},
    {"code": '01STAMP110', "description": 'STAMP PADS (BLUE)', "unit": 'Number', "quota": ''},
    {"code": '01STAMP100', "description": 'STAMP PADS (RED)', "unit": 'Number', "quota": ''},
    {"code": '01STAPL110', "description": 'STAPLER (HAND TYPE)', "unit": 'Number', "quota": ''},
    {"code": '01STAPL125', "description": 'STAPLES (24/6)', "unit": 'PACK', "quota": '1'},
    {"code": '01STAPL120', "description": 'STAPLES (64)', "unit": 'PACK', "quota": ''},
    {"code": '01STAPL095', "description": 'STAPLES (10/4)', "unit": 'PACK', "quota": ''},
    {"code": '01STAPL130', "description": 'STAPLES REMOVER', "unit": 'Number', "quota": ''},
    {"code": '01SUSPAC150', "description": 'SUPA CLIPS', "unit": '', "quota": ''},
    {"code": '01SUSPAC155', "description": 'SUPA CLIPS MACHINE', "unit": '', "quota": ''},
    {"code": '05SUSPE140', "description": 'SUSPENSION FILES', "unit": 'PACK x 50', "quota": ''},
    {"code": '01TRANS172', "description": 'A4 TRANSPARENCY FOR COPIER', "unit": 'PKT X 100', "quota": ''},
    {"code": '01PLTAG005', "description": 'TAGS MORTUARY', "unit": 'PACK x100', "quota": ''},
    {"code": '10TAPE-005', "description": 'TAPE SEALING 2"', "unit": '', "quota": ''},
    {"code": '01TAGDI01', "description": 'TAPE DISPENCER', "unit": 'Number', "quota": ''},
    {"code": '01TREAS130', "description": 'TREASURY TAGS', "unit": 'BOX', "quota": '1'},
    {"code": '01UHUST160', "description": 'UHU STICK', "unit": 'Number', "quota": ''},
    {"code": '09MARKE050', "description": 'WHITEBOARD DUSTERS', "unit": 'Number', "quota": ''},
    {"code": '', "description": 'ADULT ASSESSEMENT NURSING FORM', "unit": '', "quota": ''},
    {"code": '10DH42', "description": 'ANAESTHETIC SHEET', "unit": '', "quota": ''},
    {"code": '10DH501', "description": 'ANTICOAGULANT REFERRAL FORM', "unit": '', "quota": ''},
    {"code": '10DH302', "description": 'APPLICATION LONG VACATION LEAVE', "unit": '', "quota": ''},
    {"code": '10DH573', "description": 'APPOINTMENT FOR OF TIME IN LIEU OF OVERTIME', "unit": '', "quota": ''},
    {"code": '10DH259', "description": 'APPOINTMENT CARD', "unit": '', "quota": ''},
    {"code": '10DH572', "description": 'AUTHORISATION OF WORKING AFTER NORMAL HOURS', "unit": '', "quota": ''},
    {"code": '', "description": 'BLOOD GLUCOSE MONITOR FLOW SHEET NUR0066-', "unit": '', "quota": ''},
    {"code": '10DH563', "description": 'BLOOD ISSUE FORM', "unit": '', "quota": ''},
    {"code": '', "description": 'BONE DENSITY FORM', "unit": '', "quota": ''},
    {"code": '10DH335', "description": 'BRIF SUMMERY OF PATIENTS', "unit": '', "quota": ''},
    {"code": '10DH141', "description": 'CASE REPORT ON HOSPITAL INFECTION', "unit": '', "quota": ''},
    {"code": '10DH71', "description": 'CERTIFICATE OF ATTENDANCE', "unit": '', "quota": ''},
    {"code": '', "description": 'CONTINUITY OF NURSUING CARE FORM NUR1013V012 (MMDNA)50', "unit": '', "quota": ''},
    {"code": '10DH164', "description": 'DANGEROUS DRUGS BOOKS (2GREEN,1CHECK-BOOK)', "unit": '', "quota": ''},
    {"code": '10DH117', "description": 'DECLARATION FORM (FOR CHILD)SLH213', "unit": '', "quota": ''},
    {"code": '10DH57', "description": 'DIET FORMS', "unit": '', "quota": ''},
    {"code": '10DH64', "description": 'DKA PAT MONITORING CHART (TEMP CHART)', "unit": '', "quota": ''},
    {"code": '10DH693', "description": 'E.R.C.P. FORMS', "unit": '', "quota": ''},
    {"code": '10DH836', "description": 'ECG REQUEST FORM (WARDS) CAR/1041/01.2', "unit": '', "quota": ''},
    {"code": '10DH411', "description": 'ECHOCARDIOGRAM REQ FORM', "unit": '', "quota": ''},
    {"code": '10DH396', "description": 'EXERCISE TEST REQ FORM (CARDIAC LAB)', "unit": '', "quota": ''},
    {"code": '10DH470', "description": 'FOUR HOURLY TEMERATURE CHART', "unit": '', "quota": ''},
    {"code": '10DH350', "description": 'HOLTER MACHINE FORM (CARDIAC LAB)', "unit": '', "quota": ''},
    {"code": '', "description": '24HR FLUID BALANCE RECORD', "unit": '', "quota": ''},
    {"code": 'DH 695', "description": 'C & S FORMS BOOKLET', "unit": '', "quota": ''},
    {"code": '', "description": 'MEDICAL CERTIFICATE (BLUE)', "unit": '', "quota": ''},
    {"code": '10DH982', "description": 'MYCOLOGY LAB FORM', "unit": '', "quota": ''},
    {"code": '10DH359', "description": 'NEUROPHYSIOLOGY', "unit": '', "quota": ''},
    {"code": '', "description": 'NO BREAKS HRA/0037/V01.0', "unit": '', "quota": ''},
    {"code": '10DH668', "description": 'NOTICE OF REQ FORM STORES', "unit": '', "quota": ''},
    {"code": '10DH138', "description": 'NOTIFICATION OF CANCER ACT', "unit": '', "quota": ''},
    {"code": '10DH214', "description": "NURSES' BREAK CHANGES", "unit": '', "quota": ''},
    {"code": '10DH155', "description": 'NURSING OBSERVATION FLOW CHARTS SLH 2', "unit": '', "quota": ''},
    {"code": '10DH157', "description": 'ULTRA SOUND FORMS SLH51', "unit": '', "quota": ''},
    {"code": '10DH696', "description": 'OCCUPATIONAL THERAPY REFERRAL FORM', "unit": '', "quota": ''},
    {"code": '10DH347', "description": 'OPERATION REPORT', "unit": '', "quota": ''},
    {"code": '', "description": 'OPERATION CHECKLIST SLH 35 DH 564', "unit": '', "quota": ''},
    {"code": '10DH174', "description": 'OPERATION CONSENT SLH50', "unit": '', "quota": ''},
    {"code": '10DH528', "description": 'PERSONAL BELONGINGS', "unit": '', "quota": ''},
    {"code": '10DH505', "description": 'PHYSIOTHERAPY REFERRAL CARDS', "unit": '', "quota": ''},
    {"code": '10DH192', "description": 'POST MORTEM CONSENT', "unit": '', "quota": ''},
    {"code": '10DH178', "description": 'NURSING REPORTS SLH 76', "unit": '', "quota": ''},
    {"code": '10DH22', "description": 'REFERRAL TO OUT PATIENTS', "unit": '', "quota": ''},
    {"code": '10DH680', "description": 'RENEWAL FORM FOR DRAGS', "unit": '', "quota": ''},
    {"code": '10DH348', "description": 'REQUEST FOR EMG', "unit": '', "quota": ''},
    {"code": '10DH349', "description": 'REQUEST FOR EEG', "unit": '', "quota": ''},
    {"code": '', "description": 'REQUEST FORM FOR RESERVE ANTIBIOTIC ICU1001V01.0', "unit": '', "quota": ''},
    {"code": '10DH297', "description": 'REQUEST OT ATTEND OUT PATIENTS CLINIC', "unit": '', "quota": ''},
    {"code": '10DH1077', "description": 'RETURN OF FOREIGN PATIENTS', "unit": '', "quota": ''},
    {"code": '10DH830', "description": 'SCHEDULE V REQUEST', "unit": '', "quota": ''},
    {"code": '', "description": 'STOOL CHART', "unit": '', "quota": ''},
    {"code": '10DH89', "description": 'SPEECH AUDIOGRAM (AUDIOLOGY UNIT)', "unit": '', "quota": ''},
    {"code": '10DH355', "description": 'TEMPORARY ABSENCE SHEET', "unit": '', "quota": ''},
    {"code": '10DH18', "description": 'TO WHOM IT MAY CONCERN', "unit": '', "quota": ''},
    {"code": '10DH298', "description": 'TOXAEMIA CHART', "unit": '', "quota": ''},
    {"code": '10DH274', "description": 'LAB BLOOD FORMS SLH65', "unit": '', "quota": ''},
    {"code": '10DH277', "description": 'LAB MICOBIOLOGY FORMS(GREEN) HGT SLH', "unit": '', "quota": ''},
    {"code": '10DH277(II)', "description": 'LAB URINE FORMS (BLUE) SLH 86', "unit": '', "quota": ''},
    {"code": '10DH1006', "description": 'LIPID CLINIC', "unit": '', "quota": ''},
    {"code": '10DH311', "description": 'CONTINUATION SHEETS SLH17', "unit": '', "quota": ''},
    {"code": '10DH37', "description": 'X RAY FORM SLH93', "unit": '', "quota": ''},
    {"code": '10DH80', "description": 'X RAY REQUEST/ORDINARY', "unit": '', "quota": ''},
    {"code": '10DH387', "description": 'BLOOD TRANFUSION FORMS SLH 75', "unit": '', "quota": ''},
    {"code": '10DH394', "description": 'TOXICOLOGY REQUEST FORM SLH153', "unit": '', "quota": ''},
    {"code": '10DH467', "description": 'RELIGIOUS ASSSISTANCE IN CASE OF DEATH SLH', "unit": '', "quota": ''},
    {"code": '10DH509', "description": 'METABOLIC  CHART HGT SLH66', "unit": '', "quota": ''},
    {"code": '10DH527', "description": 'DECL.FORM DISCHARGE AT REQUEST SLH189', "unit": '', "quota": ''},
    {"code": '10DH551', "description": 'HEAD INJURY OBSERVATION CHART SLH26', "unit": '', "quota": ''},
    {"code": '10DH564', "description": 'RETURN OF ADMISSION & TRASFER SLH35', "unit": '', "quota": ''},
    {"code": '10DH586', "description": 'DECL.FORM REFUSAL OF TREATMENT SLH29', "unit": '', "quota": ''},
    {"code": '10DH614', "description": 'MOUNT SHEET', "unit": '', "quota": ''},
    {"code": '10DH628', "description": 'TREATMENT SHT. SLH193', "unit": '', "quota": ''},
    {"code": '10DH695', "description": 'VIROLOGY LAB INVESTIG FORMS', "unit": '', "quota": ''},
    {"code": '10DH889', "description": 'VITAL OBSERVATIUON FLOW CHART NUR 0092', "unit": '', "quota": ''},
    {"code": 'OPD/1013/01.0', "description": 'LUNG FUNCTION FORM', "unit": '', "quota": ''},
    {"code": '10DH75', "description": 'LETTERHEADS A6 (SMALL)', "unit": '', "quota": ''},
    {"code": '', "description": 'LETTERHEADS I,II,III', "unit": '', "quota": ''},
    {"code": '10DH769', "description": 'HIV LAB ANONYMOUS TESTING', "unit": '', "quota": ''},
    {"code": '10DH834', "description": 'REQUEST FOR NON FORMULARY ITEMS', "unit": '', "quota": ''},
    {"code": '10DH223', "description": 'CONSULTATION REQ FORMS SLH53', "unit": '', "quota": ''},
    {"code": '10DH2278/87', "description": 'IVI LABELS', "unit": '', "quota": ''},
    {"code": '10DH234', "description": 'INTAKE OUTPUT (FLUID BALANCE) SLH24', "unit": '', "quota": ''},
    {"code": '', "description": 'INTAKE OUTPUT FLOW SHEET NUR0024', "unit": '', "quota": ''},
    {"code": '10DH76', "description": 'INTAKE OUTPUT (PINK)', "unit": '', "quota": ''},
    {"code": '10DH35', "description": 'CERTIFICATE OF DEATH', "unit": '', "quota": ''},
    {"code": 'IT-RIBEL-002', "description": 'ELTRON PRITER RIBBON 110MM X 91M', "unit": 'Number', "quota": '1'},
    {"code": '07INKBA020', "description": 'ENDORSING INK BLACK', "unit": 'Number', "quota": '1'},
    {"code": 'IT-LABEL-003', "description": 'ELTRON PRINTER LABELS 50 X 22 MM', "unit": 'Number', "quota": '1'},
]
