from django.urls import path

from . import views

app_name = "clinic"

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("ward/", views.ward, name="ward"),
    path("letters/discharge/", views.discharge_letter, name="discharge_letter"),
    path("letters/discharge/<uuid:patient_id>/", views.discharge_letter,
         name="discharge_letter_for"),
    path("reports/", views.reports, name="reports"),
    path("ordering/", views.ordering_forms, name="ordering_forms"),
    path("ordering/esrf/", views.esrf_form, name="esrf_form"),
    path("ordering/form/<slug:slug>/", views.order_form, name="order_form"),
    path("documents/", views.clinic_documents, name="clinic_documents"),
    path("documents/<uuid:pk>/", views.ordering_document_detail, name="ordering_document_detail"),
    path("library/", views.library, name="library"),
    path("library/file-discharge-letter/", views.file_discharge_letter,
         name="file_discharge_letter"),
    path("library/<uuid:pk>/file/", views.library_file, name="library_file"),
    path("library/<uuid:pk>/delete/", views.library_delete, name="library_delete"),
    path("cpsu/", views.cpsu, name="cpsu"),
    path("cpsu/tenders/", views.cpsu_tenders, name="cpsu_tenders"),
    path("cpsu/tenders/new/", views.tender_new, name="tender_new"),
    path("cpsu/tenders/current/", views.tenders_current, name="tenders_current"),
    path("cpsu/tenders/closed/", views.tenders_closed, name="tenders_closed"),
    path("cpsu/tenders/<uuid:pk>/", views.tender_edit, name="tender_edit"),
    path("cpsu/tenders/<uuid:pk>/delete/", views.tender_delete, name="tender_delete"),
    path("cpsu/appliances/", views.cpsu_appliances, name="cpsu_appliances"),
    path("cpsu/appliances/<uuid:pk>/delete/", views.cpsu_appliance_delete,
         name="cpsu_appliance_delete"),
    path("cpsu/specifications/", views.cpsu_specifications, name="cpsu_specifications"),
    path("cpsu/specifications/<uuid:pk>/delete/", views.cpsu_specification_delete,
         name="cpsu_specification_delete"),
    path("roster/", views.roster, name="roster"),
    path("roster/staff/add/", views.roster_staff_add, name="roster_staff_add"),
    path("roster/staff/<uuid:pk>/delete/", views.roster_staff_delete, name="roster_staff_delete"),
    path("roster/shift/set/", views.roster_shift_set, name="roster_shift_set"),
    path("roster/overtime/add/", views.overtime_add, name="overtime_add"),
    path("roster/overtime/<uuid:pk>/delete/", views.overtime_delete, name="overtime_delete"),
    path("roster/til/add/", views.til_add, name="til_add"),
    path("roster/til/<uuid:pk>/delete/", views.til_delete, name="til_delete"),
    path("reminders/", views.reminders, name="reminders"),
    path("reminders/<uuid:pk>/toggle/", views.reminder_toggle, name="reminder_toggle"),
    path("reminders/<uuid:pk>/send/", views.reminder_send, name="reminder_send"),
    path("reminders/<uuid:pk>/delete/", views.reminder_delete, name="reminder_delete"),
    path("diary/", views.diary, name="diary"),
    path("diary/<uuid:pk>/edit/", views.diary_entry_edit, name="diary_entry_edit"),
    path("diary/<uuid:pk>/delete/", views.diary_entry_delete, name="diary_entry_delete"),
    path("admin-users/", views.admin_users, name="admin_users"),
    path("admin-users/<int:pk>/edit/", views.admin_user_edit, name="admin_user_edit"),
    path("admin-users/password/", views.admin_password_self, name="admin_password_self"),
    path("admin-users/<int:pk>/password/", views.admin_password_set, name="admin_password_set"),
    path("more/", views.more_tools, name="more_tools"),
    path("pathways/<uuid:pk>/", views.pathway_detail, name="pathway_detail"),
    path("pathways/<uuid:pk>/encounter/", views.encounter_new, name="encounter_new"),
    path("patients/<uuid:patient_id>/profile/", views.patient_profile, name="patient_profile"),
    path("appointments/", views.appointments, name="appointments"),
    path("appointments/patients.json", views.appointment_patient_search,
         name="appointment_patient_search"),
    path("appointments/capacity.json", views.appointment_capacity,
         name="appointment_capacity"),
    path("patients/add/", views.add_patient, name="add_patient"),
    path("patients/", views.patient_list, name="patient_list"),
    path("patients/<uuid:patient_id>/card.json", views.patient_card, name="patient_card"),
    path("patients/<uuid:patient_id>/", views.patient_detail, name="patient_detail"),
]
